#!/bin/bash
# This script renames the Gerber files generated by KiCAD according
# to elecrows naming scheme and puts them into a zip file.

NAME="acs-display-grabber"
mkdir -p elecrow

# Layers
cp ${NAME}-F.Cu.gbr elecrow/${NAME}.GTL
cp ${NAME}-B.Cu.gbr elecrow/${NAME}.GBL

# (Anti) Solder Mask
cp ${NAME}-F.Mask.gbr elecrow/${NAME}.GTS
cp ${NAME}-B.Mask.gbr elecrow/${NAME}.GBS

# Silk Layer
cp ${NAME}-F.SilkS.gbr elecrow/${NAME}.GTO
cp ${NAME}-B.SilkS.gbr elecrow/${NAME}.GBO

# Mechanical
cp ${NAME}-Edge.Cuts.gbr elecrow/${NAME}.GML

# Drill
cp ${NAME}.drl elecrow/${NAME}.TXT

cd elecrow
zip ../${NAME}.zip ${NAME}.GTL ${NAME}.GBL ${NAME}.GTS ${NAME}.GBS ${NAME}.GTO ${NAME}.GBO ${NAME}.GML ${NAME}.TXT
rm -rf elecrow
cd ..
